networks:
  gitea:
    external: false
  proxy:
    external: true
  finance_finance:
    external: true

services:
  server:
    image: docker.gitea.com/gitea:1.25.3
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    networks:
      - gitea
      - proxy
    volumes:
      - ${DATA_PATH}/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gitea.rule=Host(`gitea.masahome`)"
      - "traefik.http.routers.gitea.entrypoints=web"
      - "traefik.http.services.gitea.loadbalancer.server.port=80"

  runner:
    image: gitea/act_runner:latest
    container_name: runner
    restart: always
    networks:
      - gitea
      - finance_finance
      - proxy
    environment:
      - CONFIG_FILE=/config.yaml
      - GITEA_INSTANCE_URL=http://gitea.masahome
      - GITEA_RUNNER_REGISTRATION_TOKEN=4Jj9Fg9VRgVIZpDukWVlfO1iQBjDhWLGmCImOyGg
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config.yaml:/config.yaml
