services:
  db:
    container_name: odoo_foto_db
    image: postgres:16
    user: root
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo19@2026
      - POSTGRES_DB=postgres
    restart: unless-stopped
    volumes:
      - ${DATA_PATH}/postgres-foto:/var/lib/postgresql/data
    networks:
      - odoo

  odoo19:
    image: odoo:19
    user: root
    depends_on:
      - db
    restart: unless-stopped
    environment:
      - HOST=odoo_foto_db
      - USER=odoo
      - PASSWORD=odoo19@2026
      - TZ=America/Sao_Paulo
    volumes:
      - ${DATA_PATH}/odoo-foto/web-data:/var/lib/odoo
      - ${DATA_PATH}/odoo-foto/addons:/mnt/extra-addons
    networks:
      - proxy
      - odoo
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.odoofoto.rule=Host(`erpfoto.masahome.online`)"
      - "traefik.http.routers.odoofoto.entrypoints=web"
      - "traefik.http.services.odoofoto.loadbalancer.server.port=8069"

networks:
  proxy:
    external: true
  odoo:
